const LanguageMapper = {
  auto: "Voice Detection",
  th: "Thai",
  en: "English",
  es: "Spanish",
  fr: "French",
  de: "German",
  af: "Afrikaans",
  am: "Amharic",
  ar: "Arabic",
  bg: "Bulgarian",
  bn: "Bengali",
  bs: "Bosnian",
  ca: "Catalan",
  cs: "Czech",
  cy: "Welsh",
  da: "Danish",
  el: "Greek",
  et: "Estonian",
  eu: "Basque",
  fi: "Finnish",
  ga: "Galician",
  gu: "Gujarati",
  ha: "Hausa",
  hi: "Hindi",
  hr: "Croatian",
  hu: "Hungarian",
  id: "Indonesian",
  is: "Icelandic",
  it: "Italian",
  iw: "Hebrew",
  ja: "Japanese",
  jv: "Javanese",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  la: "Latin",
  lv: "Latvian",
  ml: "Malayalam",
  mr: "Marathi",
  ms: "Malay",
  my: "Myanmar (Burmese)",
  ne: "Nepali",
  nl: "Dutch",
  no: "Norwegian",
  pa: "Punjabi (Gurmukhi)",
  pl: "Polish",
  pt_PT: "Portuguese (Portugal)",
  pt_BR: "Portuguese (Brazil)",
  ro: "Romanian",
  ru: "Russian",
  si: "Sinhala",
  sk: "Slovak",
  sq: "Albanian",
  sr: "Serbian",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  tl: "Filipino",
  tr: "Turkish",
  uk: "Ukrainian",
  ur: "Urdu",
  vi: "Vietnamese",
  yue: "Cantonese",
  zh_CN: "Chinese (Simplified)",
  zh_TW: "Chinese (Mandarin/Taiwan)",
  zh: "Chinese (Mandarin)",
};

export default LanguageMapper;
